apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-firtcityuc-com-tls
spec:
  secretName: k8s-firtcityuc-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: firstcityuc.com
  dnsNames:
    - firstcityuc.com
    - www.firstcityuc.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - firstcityuc.com
          - www.firstcityuc.com